version: "2"
run:
  timeout: 5m
formatters:
  enable:
    - goimports
linters:
  enable:
    - nakedret
    - misspell
    - ineffassign
    - goconst
    - errcheck
    - dupl
    - unparam
    - revive
    - staticcheck
    - unused
    - unconvert
    - gocyclo
    - gosec
  settings:
    revive:
      rules:
        - name: dot-imports
          disabled: true
        - name: var-naming
          arguments:
            - []
            - []
            - - skipPackageNameChecks: true
issues:
  exclude-rules:

    - linters:
        - gosec
      # these exclusion rules are for current failures in the code base for gosec which are
      # excluded for future PRs which include:
      # G110: Potential DoS vulnerability via decompression bomb
      # G204: Audit use of command execution
      # G306: Poor file permissions used when writing to a new file
      # G404: Insecure random number source (rand)
      # G601: Implicit memory aliasing of items from a range statement
      text: 'G110|G601|G404|G204|G306'
