name: Integration Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Gos
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.9
      - name: Install tox
        run: pip install tox
      - name: Integrate Test
        run: make test-integration
